version: '3'

services:
  postgresql:
    image: postgres:latest
    environment:
      - POSTGRES_DB=distillery
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=secret
    ports:
      - "5434:5432"

  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - "22181:2181"

  kafka:
    image: confluentinc/cp-kafka:latest
    depends_on:
      - zookeeper
    ports:
      - "29092:29092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092,PLAINTEXT_HOST://localhost:29092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_LOG_RETENTION_MS: 10000
      KAFKA_LOG_RETENTION_CHECK_INTERVAL_MS: 5000

  kafka_ui:
    image: provectuslabs/kafka-ui:latest
    depends_on:
      - kafka
    ports:
      - "8001:8080"
    environment:
      KAFKA_CLUSTERS_0_ZOOKEEPER: zookeeper:2181
      KAFKA_CLUSTERS_0_NAME: local
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: kafka:9092

#  kibana:
#    image: docker.elastic.co/kibana/kibana:8.4.1
#    volumes:
#      - "./kibana.yml:/usr/share/kibana/config/kibana.yml"
#    restart: always
#    ports:
#      - "5601:5601"
#    links:
#      - elasticsearch
#    depends_on:
#      - elasticsearch
#  elasticsearch:
#    image: docker.elastic.co/elasticsearch/elasticsearch:8.4.1
#    environment:
#      - cluster.name=docker-cluster
#      - bootstrap.memory_lock=true
#      - xpack.security.enabled=false
#      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
#    ulimits:
#      memlock:
#        soft: -1
#        hard: -1
#    volumes:
#      - "./esdata:/usr/share/elasticsearch/data"
#    ports:
#      - "9200:9200"
#  logstash:
#    image: docker.elastic.co/logstash/logstash:8.4.1
#    volumes:
#      - "./logstash.conf:/config-dir/logstash.conf"
#    restart: always
#    command: logstash -f /config-dir/logstash.conf
#    ports:
#      - "9600:9600"
#      - "7777:7777"
#    links:
#      - elasticsearch
#      - kafka
